// <auto-generated />
namespace Iqraa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emailRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202101171409403_emailRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
