//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iqraa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iqraa.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre about the Fonder of the centre ( his biography). programs offered in our centre news about the centre. what&apos;s new about the centre.
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center News.
        /// </summary>
        public static string CenterNews {
            get {
                return ResourceManager.GetString("CenterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center&apos;s Programs.
        /// </summary>
        public static string CenterPrograms {
            get {
                return ResourceManager.GetString("CenterPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s message.
        /// </summary>
        public static string CentreMessage {
            get {
                return ResourceManager.GetString("CentreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facilitating learning the Arabic reading to read the nobel Quran.
        /// </summary>
        public static string CentreMessageValue {
            get {
                return ResourceManager.GetString("CentreMessageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre offers its programs for those who desire to learn Arabic reading and cannot read it, for beginners in learning it, and for those who aren&apos;t fluent in it..
        /// </summary>
        public static string CentreOffer {
            get {
                return ResourceManager.GetString("CentreOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s vision.
        /// </summary>
        public static string CentreVision {
            get {
                return ResourceManager.GetString("CentreVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable those who can&apos;t read the nobel Quran to read it.
        /// </summary>
        public static string CentreVisionValue {
            get {
                return ResourceManager.GetString("CentreVisionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first program.
        /// </summary>
        public static string FirstProgram {
            get {
                return ResourceManager.GetString("FirstProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program offered to those who never know Arabic reading, or have a little background, but cannot read the Noble Quran.
        ///It is a program that can be offered to both native Arabic speakers and non-Arabic speakers.
        ///Duration of the Program:
        /// 60 training hours in 60 or 30 training days..
        /// </summary>
        public static string FirstProgramDescription {
            get {
                return ResourceManager.GetString("FirstProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic to read the Noble Qur’an for beginners..
        /// </summary>
        public static string FirstProgramHeading {
            get {
                return ResourceManager.GetString("FirstProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder of the Center.
        /// </summary>
        public static string Founder {
            get {
                return ResourceManager.GetString("Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder Current Job.
        /// </summary>
        public static string FounderCurrentJob {
            get {
                return ResourceManager.GetString("FounderCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager of Iqraa Center for Arabic Language Learn.
        /// </summary>
        public static string FounderCurrentJobValue {
            get {
                return ResourceManager.GetString("FounderCurrentJobValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s Previous Experience.
        /// </summary>
        public static string FounderExperience {
            get {
                return ResourceManager.GetString("FounderExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor of teaching Arabic to students of the first three grades of the primary school.
        /// </summary>
        public static string FounderExperienceValueLine1 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary school Headmaster.
        /// </summary>
        public static string FounderExperienceValueLine2 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic teacher.
        /// </summary>
        public static string FounderExperienceValueLine3 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s interests.
        /// </summary>
        public static string FounderInterest {
            get {
                return ResourceManager.GetString("FounderInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic reading to non-Arabs..
        /// </summary>
        public static string FounderInterestValue {
            get {
                return ResourceManager.GetString("FounderInterestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahd bin Saleh bin Abdullah Al-Twaijri.
        /// </summary>
        public static string FounderName {
            get {
                return ResourceManager.GetString("FounderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Qualifications of the Founder.
        /// </summary>
        public static string FounderQualifications {
            get {
                return ResourceManager.GetString("FounderQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master in Linguistics from Umm Al-Qura University in Makkah Al-Mukarramah 2019..
        /// </summary>
        public static string FounderQualificationsValueLine1 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA in the Arabic language from Imam Muhammad bin Saud Islamic University, 2002.
        /// </summary>
        public static string FounderQualificationsValueLine2 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Founder&apos;s Specialty.
        /// </summary>
        public static string FounderSpecialty {
            get {
                return ResourceManager.GetString("FounderSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic language.
        /// </summary>
        public static string FounderSpecialtyValue {
            get {
                return ResourceManager.GetString("FounderSpecialtyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s writings.
        /// </summary>
        public static string FounderWritings {
            get {
                return ResourceManager.GetString("FounderWritings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book of &quot;learn how to read the Noble Qur’an in thirty days&quot;.
        /// </summary>
        public static string FounderWritingsValue {
            get {
                return ResourceManager.GetString("FounderWritingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taqra Center.
        /// </summary>
        public static string IQRAACentre {
            get {
                return ResourceManager.GetString("IQRAACentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A centre is interested in teaching Arabic for all, aiming for facilitating learning Arabic reading and shortening the time required for that, to fulfil a hope that many Muslims have, which is reading the Noble Quran..
        /// </summary>
        public static string IQRAACentreP {
            get {
                return ResourceManager.GetString("IQRAACentreP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre is looking for the best ways and the most appropriate means to teach Arabic and be able to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP2 {
            get {
                return ResourceManager.GetString("IQRAACentreP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undoubtedly, the Arabic language is characterized by the proximity of its spoken sounds to its written letters and words, which facilitates and helps to learn Arabic reading thus learn to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP3 {
            get {
                return ResourceManager.GetString("IQRAACentreP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Program.
        /// </summary>
        public static string SecondProgram {
            get {
                return ResourceManager.GetString("SecondProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program that helps students to correct their mistakes in reading the Noble Qur’an by addressing the causes of mistakes.Our goal in this program is to treat those mistakes from their roots. 
        ///It is a program that can be offered to both native Arabic speakers and non-Arabic speakers.
        /// </summary>
        public static string SecondProgramDescription {
            get {
                return ResourceManager.GetString("SecondProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Reading of the Noble Quran..
        /// </summary>
        public static string SecondProgramHeading {
            get {
                return ResourceManager.GetString("SecondProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
    }
}
