//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iqraa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iqraa.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre about the Fonder of the centre ( his biography). programs offered in our centre news about the centre. what&apos;s new about the centre.
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a center concerned with teaching Arabic reading to everyone with the ultimate objective of streamlining the learning experience and making it time-effective, in order to fulfill the aspiration of many Muslims, which is to read the Holy Quran..
        /// </summary>
        public static string AboutUsP1 {
            get {
                return ResourceManager.GetString("AboutUsP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The center is seeking the most effective approaches and the optimal Means for teaching Arabic reading and Empowerment in the reading of the Holy Quran..
        /// </summary>
        public static string AboutUsP2 {
            get {
                return ResourceManager.GetString("AboutUsP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the belief of the center that Arabic is a phonetic language with a close correspondence between its spoken and written components, a crucial factor in facilitating the learning of Arabic reading..
        /// </summary>
        public static string AboutUsP3 {
            get {
                return ResourceManager.GetString("AboutUsP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (13) lessons ( Teaching Arabic Letters ).
        /// </summary>
        public static string ArabicLettersLearn {
            get {
                return ResourceManager.GetString("ArabicLettersLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additions and omissions in Arabic writing.
        /// </summary>
        public static string Article1 {
            get {
                return ResourceManager.GetString("Article1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinctions in written form between the Quran and standard Arabic.
        /// </summary>
        public static string Article2 {
            get {
                return ResourceManager.GetString("Article2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special writing and reading rules of the Holy Qur’an.
        /// </summary>
        public static string Article3 {
            get {
                return ResourceManager.GetString("Article3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to initiate the teaching and learning to read the Holy Qur&apos;an.
        /// </summary>
        public static string Article4 {
            get {
                return ResourceManager.GetString("Article4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/articles/articles-en.png.
        /// </summary>
        public static string ArticleImg {
            get {
                return ResourceManager.GetString("ArticleImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1oY3IINAj9AhhR7FtQjDnhVzqx6WcVTV_/view?usp=sharing.
        /// </summary>
        public static string ArticleURL1 {
            get {
                return ResourceManager.GetString("ArticleURL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1pPl2W4SHywWWL1qWyoOMNjTNayVSSolc/view?usp=sharing.
        /// </summary>
        public static string ArticleURL2 {
            get {
                return ResourceManager.GetString("ArticleURL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1nFaOGekov3TAOed88n17TVhutnGBFcpd/view?usp=sharing.
        /// </summary>
        public static string ArticleURL3 {
            get {
                return ResourceManager.GetString("ArticleURL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1nsQv6TCWLF3_6LLQWHSGereoNjpOJdVP/view?usp=drive_link.
        /// </summary>
        public static string ArticleURL4 {
            get {
                return ResourceManager.GetString("ArticleURL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/books/en-b1.jpeg.
        /// </summary>
        public static string BookImg1 {
            get {
                return ResourceManager.GetString("BookImg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1_O3elIzfiSi6snyczo2Zp5mdOoQVPne-/view.
        /// </summary>
        public static string BookURL1 {
            get {
                return ResourceManager.GetString("BookURL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center News.
        /// </summary>
        public static string CenterNews {
            get {
                return ResourceManager.GetString("CenterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center&apos;s Programs.
        /// </summary>
        public static string CenterPrograms {
            get {
                return ResourceManager.GetString("CenterPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s message.
        /// </summary>
        public static string CentreMessage {
            get {
                return ResourceManager.GetString("CentreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facilitating learning the Arabic reading to read the nobel Quran.
        /// </summary>
        public static string CentreMessageValue {
            get {
                return ResourceManager.GetString("CentreMessageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre offers its programs for those who desire to learn Arabic reading and cannot read it, for beginners in learning it, and for those who aren&apos;t fluent in it..
        /// </summary>
        public static string CentreOffer {
            get {
                return ResourceManager.GetString("CentreOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s vision.
        /// </summary>
        public static string CentreVision {
            get {
                return ResourceManager.GetString("CentreVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable those who can&apos;t read the nobel Quran to read it.
        /// </summary>
        public static string CentreVisionValue {
            get {
                return ResourceManager.GetString("CentreVisionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج الخامس.
        /// </summary>
        public static string FifthProgram {
            get {
                return ResourceManager.GetString("FifthProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing and addressing Holy Quran reading deficiencies program for beginners
        ///
        ///Through this program, the student&apos;s proficiency in Quranic vocabulary is evaluated, areas of weakness are pinpointed, and a customized program is designed to improve these skills.
        ///
        ///Our program targets the root of reading difficulties rather than solely correcting word errors made by students..
        /// </summary>
        public static string FifthProgramDescription {
            get {
                return ResourceManager.GetString("FifthProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing and addressing Holy Quran reading deficiencies program for beginners.
        /// </summary>
        public static string FifthProgramHeading {
            get {
                return ResourceManager.GetString("FifthProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITQAN (Mastering literal Arabic reading skills).
        /// </summary>
        public static string FirstBook {
            get {
                return ResourceManager.GetString("FirstBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First level.
        /// </summary>
        public static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial level.
        /// </summary>
        public static string FirstProgram {
            get {
                return ResourceManager.GetString("FirstProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic letters and reading trilateral words with Fat-ha  -13 lessons.
        /// </summary>
        public static string FirstProgramDescription {
            get {
                return ResourceManager.GetString("FirstProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures are delivered in three different methods:.
        /// </summary>
        public static string FirstProgramDescription2 {
            get {
                return ResourceManager.GetString("FirstProgramDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Basic Arabic Reading Principles program.
        /// </summary>
        public static string FirstProgramHeading {
            get {
                return ResourceManager.GetString("FirstProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the classroom..
        /// </summary>
        public static string FirstProgramlist1 {
            get {
                return ResourceManager.GetString("FirstProgramlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the virtual classroom (via learning platforms like Zoom). Where the student learns the letter sounds with the short vowel (Fat-ha), uses simple writing worksheets to practice writing the letters forms at the beginning, middle and end of the word in order to memorize the letter shapes in their different positions, and reads trilateral words with the Fat-ha which are consisted of letters previously learned.
        /// </summary>
        public static string FirstProgramlist2 {
            get {
                return ResourceManager.GetString("FirstProgramlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via recorded video lessons on Taqraa Center for Holy Quran Literacy YouTube channel..
        /// </summary>
        public static string FirstProgramlist3 {
            get {
                return ResourceManager.GetString("FirstProgramlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder of the Center.
        /// </summary>
        public static string Founder {
            get {
                return ResourceManager.GetString("Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder Current Job.
        /// </summary>
        public static string FounderCurrentJob {
            get {
                return ResourceManager.GetString("FounderCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager of Iqraa Center for Arabic Language Learn.
        /// </summary>
        public static string FounderCurrentJobValue {
            get {
                return ResourceManager.GetString("FounderCurrentJobValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s Previous Experience.
        /// </summary>
        public static string FounderExperience {
            get {
                return ResourceManager.GetString("FounderExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor of teaching Arabic to students of the first three grades of the primary school.
        /// </summary>
        public static string FounderExperienceValueLine1 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary school Headmaster.
        /// </summary>
        public static string FounderExperienceValueLine2 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic teacher.
        /// </summary>
        public static string FounderExperienceValueLine3 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s interests.
        /// </summary>
        public static string FounderInterest {
            get {
                return ResourceManager.GetString("FounderInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic reading to non-Arabs..
        /// </summary>
        public static string FounderInterestValue {
            get {
                return ResourceManager.GetString("FounderInterestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahd bin Saleh bin Abdullah Al-Twaijri.
        /// </summary>
        public static string FounderName {
            get {
                return ResourceManager.GetString("FounderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Qualifications of the Founder.
        /// </summary>
        public static string FounderQualifications {
            get {
                return ResourceManager.GetString("FounderQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master in Linguistics from Umm Al-Qura University in Makkah Al-Mukarramah 2019..
        /// </summary>
        public static string FounderQualificationsValueLine1 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA in the Arabic language from Imam Muhammad bin Saud Islamic University, 2002.
        /// </summary>
        public static string FounderQualificationsValueLine2 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Founder&apos;s Specialty.
        /// </summary>
        public static string FounderSpecialty {
            get {
                return ResourceManager.GetString("FounderSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic language.
        /// </summary>
        public static string FounderSpecialtyValue {
            get {
                return ResourceManager.GetString("FounderSpecialtyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s writings.
        /// </summary>
        public static string FounderWritings {
            get {
                return ResourceManager.GetString("FounderWritings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book of &quot;learn how to read the Noble Qur’an in thirty days&quot;.
        /// </summary>
        public static string FounderWritingsValue {
            get {
                return ResourceManager.GetString("FounderWritingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Program.
        /// </summary>
        public static string FourthProgram {
            get {
                return ResourceManager.GetString("FourthProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through this program, the student&apos;s proficiency in a set of vocabularies is evaluated, areas of weakness are pinpointed, and a customized program is designed to improve these skills..
        /// </summary>
        public static string FourthProgramDescription {
            get {
                return ResourceManager.GetString("FourthProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing and addressing reading deficiencies program.
        /// </summary>
        public static string FourthProgramHeading {
            get {
                return ResourceManager.GetString("FourthProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taqra Center.
        /// </summary>
        public static string IQRAACentre {
            get {
                return ResourceManager.GetString("IQRAACentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A centre is interested in teaching Arabic for all, aiming for facilitating learning Arabic reading and shortening the time required for that, to fulfil a hope that many Muslims have, which is reading the Noble Quran..
        /// </summary>
        public static string IQRAACentreP {
            get {
                return ResourceManager.GetString("IQRAACentreP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre is looking for the best ways and the most appropriate means to teach Arabic and be able to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP2 {
            get {
                return ResourceManager.GetString("IQRAACentreP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undoubtedly, the Arabic language is characterized by the proximity of its spoken sounds to its written letters and words, which facilitates and helps to learn Arabic reading thus learn to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP3 {
            get {
                return ResourceManager.GetString("IQRAACentreP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqraa Program.
        /// </summary>
        public static string IQRAAProgram {
            get {
                return ResourceManager.GetString("IQRAAProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of downloads.
        /// </summary>
        public static string NumberOfDownloads {
            get {
                return ResourceManager.GetString("NumberOfDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Message.
        /// </summary>
        public static string OurMessage {
            get {
                return ResourceManager.GetString("OurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolve the best ways and means of promoting and facilitating the learning of Arabic reading..
        /// </summary>
        public static string OurMessageP1 {
            get {
                return ResourceManager.GetString("OurMessageP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vision.
        /// </summary>
        public static string OurVision {
            get {
                return ResourceManager.GetString("OurVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisting individuals in achieving their aspirations of becoming proficient in reading Arabic.
        /// </summary>
        public static string OurVisionP1 {
            get {
                return ResourceManager.GetString("OurVisionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( 20 ) lessons ( Teaching Holy Quran reading ).
        /// </summary>
        public static string QuranReading {
            get {
                return ResourceManager.GetString("QuranReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Teaching Arabic reading skills ) ( 25 lessons ( Lessons from ITQAN book for mastering literal Arabic reading skills).
        /// </summary>
        public static string ReadingSkillsLearn {
            get {
                return ResourceManager.GetString("ReadingSkillsLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITQAN (Mastering literal Arabic reading skills with some words pronunciation transliteration).
        /// </summary>
        public static string SecondBook {
            get {
                return ResourceManager.GetString("SecondBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second level.
        /// </summary>
        public static string SecondLevel {
            get {
                return ResourceManager.GetString("SecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Program.
        /// </summary>
        public static string SecondProgram {
            get {
                return ResourceManager.GetString("SecondProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program that helps students to correct their mistakes in reading the Noble Qur’an by addressing the causes of mistakes.Our goal in this program is to treat those mistakes from their roots. 
        ///It is a program that can be offered to both native Arabic speakers and non-Arabic speakers.
        /// </summary>
        public static string SecondProgramDescription {
            get {
                return ResourceManager.GetString("SecondProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures are delivered in three different methods:.
        /// </summary>
        public static string SecondProgramDescription2 {
            get {
                return ResourceManager.GetString("SecondProgramDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic Reading Skills program.
        /// </summary>
        public static string SecondProgramHeading {
            get {
                return ResourceManager.GetString("SecondProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the classroom..
        /// </summary>
        public static string SecondProgramlist1 {
            get {
                return ResourceManager.GetString("SecondProgramlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the virtual classroom (via learning platforms like Zoom) - Chat room.
        /// </summary>
        public static string SecondProgramlist2 {
            get {
                return ResourceManager.GetString("SecondProgramlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the virtual classroom (via learning platforms like Zoom) -one on one chat.
        /// </summary>
        public static string SecondProgramlist3 {
            get {
                return ResourceManager.GetString("SecondProgramlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via recorded video lessons on  (        ) platform..
        /// </summary>
        public static string SecondProgramlist4 {
            get {
                return ResourceManager.GetString("SecondProgramlist4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The third level.
        /// </summary>
        public static string ThirdLevel {
            get {
                return ResourceManager.GetString("ThirdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Program.
        /// </summary>
        public static string ThirdProgram {
            get {
                return ResourceManager.GetString("ThirdProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is structured into three levels:.
        /// </summary>
        public static string ThirdProgramDescription {
            get {
                return ResourceManager.GetString("ThirdProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Holy Quran Reading Program for Beginners.
        /// </summary>
        public static string ThirdProgramHeading {
            get {
                return ResourceManager.GetString("ThirdProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/videos/vd1-en.png.
        /// </summary>
        public static string VideoImg1 {
            get {
                return ResourceManager.GetString("VideoImg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Reading Principles.
        /// </summary>
        public static string VideoPlaylistName1 {
            get {
                return ResourceManager.GetString("VideoPlaylistName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtube.com/playlist?list=PLNUNHIo8EZJ9JY-G-zrDGQD8ipzDwioeD&amp;si=x9nfsHk99bC3d2X3.
        /// </summary>
        public static string VideoURL1 {
            get {
                return ResourceManager.GetString("VideoURL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Are We.
        /// </summary>
        public static string WhoAreWe {
            get {
                return ResourceManager.GetString("WhoAreWe", resourceCulture);
            }
        }
    }
}
