//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iqraa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iqraa.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the centre about the Fonder of the centre ( his biography). programs offered in our centre news about the centre. what&apos;s new about the centre.
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم الحروف العربية - 13 درسا.
        /// </summary>
        public static string ArabicLettersLearn {
            get {
                return ResourceManager.GetString("ArabicLettersLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additions and omissions in Arabic writing.
        /// </summary>
        public static string Article1 {
            get {
                return ResourceManager.GetString("Article1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinctions in written form between the Quran and standard Arabic.
        /// </summary>
        public static string Article2 {
            get {
                return ResourceManager.GetString("Article2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special writing and reading rules of the Holy Qur’an.
        /// </summary>
        public static string Article3 {
            get {
                return ResourceManager.GetString("Article3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to initiate the teaching and learning to read the Holy Qur&apos;an.
        /// </summary>
        public static string Article4 {
            get {
                return ResourceManager.GetString("Article4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center News.
        /// </summary>
        public static string CenterNews {
            get {
                return ResourceManager.GetString("CenterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center&apos;s Programs.
        /// </summary>
        public static string CenterPrograms {
            get {
                return ResourceManager.GetString("CenterPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s message.
        /// </summary>
        public static string CentreMessage {
            get {
                return ResourceManager.GetString("CentreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facilitating learning the Arabic reading to read the nobel Quran.
        /// </summary>
        public static string CentreMessageValue {
            get {
                return ResourceManager.GetString("CentreMessageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre offers its programs for those who desire to learn Arabic reading and cannot read it, for beginners in learning it, and for those who aren&apos;t fluent in it..
        /// </summary>
        public static string CentreOffer {
            get {
                return ResourceManager.GetString("CentreOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre&apos;s vision.
        /// </summary>
        public static string CentreVision {
            get {
                return ResourceManager.GetString("CentreVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable those who can&apos;t read the nobel Quran to read it.
        /// </summary>
        public static string CentreVisionValue {
            get {
                return ResourceManager.GetString("CentreVisionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج الخامس.
        /// </summary>
        public static string FifthProgram {
            get {
                return ResourceManager.GetString("FifthProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم في هذا البرنامج اختبار الطالب في مجموعة من الكلمات، و يتم تحديد المهارات التي لا يتقنها الطالب، ووضع برنامج مختصر لعلاج المهارات التي لا يتقنها فقط.
        /// </summary>
        public static string FifthProgramDescription {
            get {
                return ResourceManager.GetString("FifthProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج تشخيص وعلاج الضعف القرائي.
        /// </summary>
        public static string FifthProgramHeading {
            get {
                return ResourceManager.GetString("FifthProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITQAN (Mastering literal Arabic reading skills).
        /// </summary>
        public static string FirstBook {
            get {
                return ResourceManager.GetString("FirstBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الأول.
        /// </summary>
        public static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first program.
        /// </summary>
        public static string FirstProgram {
            get {
                return ResourceManager.GetString("FirstProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program offered to those who never know Arabic reading, or have a little background, but cannot read the Noble Quran.
        ///It is a program that can be offered to both native Arabic speakers and non-Arabic speakers.
        ///Duration of the Program:
        /// 60 training hours in 60 or 30 training days..
        /// </summary>
        public static string FirstProgramDescription {
            get {
                return ResourceManager.GetString("FirstProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم التعلم فيه بإحدى الطرق التالية:.
        /// </summary>
        public static string FirstProgramDescription2 {
            get {
                return ResourceManager.GetString("FirstProgramDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic to read the Noble Qur’an for beginners..
        /// </summary>
        public static string FirstProgramHeading {
            get {
                return ResourceManager.GetString("FirstProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الفصل الحقيقي..
        /// </summary>
        public static string FirstProgramlist1 {
            get {
                return ResourceManager.GetString("FirstProgramlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الفصل الافتراضي ( عبر منصات التعليم مثل زووم ): وفيه يتم استخدام نماذج كتابية بسيطة يكتب فيها الطالب الحرف في أول ووسط وآخر الكلمة ليتقن الطالب حفظ أشكال الحروف في مواضعها المختلفة ويتم تعلم قراءة كلمات ثلاثية مفتوحة درس الطالب جميع حروفها ).
        /// </summary>
        public static string FirstProgramlist2 {
            get {
                return ResourceManager.GetString("FirstProgramlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خلال دروس الفيديو المسجلة في قناة مركز تقرأ على يوتيوب..
        /// </summary>
        public static string FirstProgramlist3 {
            get {
                return ResourceManager.GetString("FirstProgramlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder of the Center.
        /// </summary>
        public static string Founder {
            get {
                return ResourceManager.GetString("Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder Current Job.
        /// </summary>
        public static string FounderCurrentJob {
            get {
                return ResourceManager.GetString("FounderCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager of Iqraa Center for Arabic Language Learn.
        /// </summary>
        public static string FounderCurrentJobValue {
            get {
                return ResourceManager.GetString("FounderCurrentJobValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s Previous Experience.
        /// </summary>
        public static string FounderExperience {
            get {
                return ResourceManager.GetString("FounderExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor of teaching Arabic to students of the first three grades of the primary school.
        /// </summary>
        public static string FounderExperienceValueLine1 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary school Headmaster.
        /// </summary>
        public static string FounderExperienceValueLine2 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic teacher.
        /// </summary>
        public static string FounderExperienceValueLine3 {
            get {
                return ResourceManager.GetString("FounderExperienceValueLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s interests.
        /// </summary>
        public static string FounderInterest {
            get {
                return ResourceManager.GetString("FounderInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Arabic reading to non-Arabs..
        /// </summary>
        public static string FounderInterestValue {
            get {
                return ResourceManager.GetString("FounderInterestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahd bin Saleh bin Abdullah Al-Twaijri.
        /// </summary>
        public static string FounderName {
            get {
                return ResourceManager.GetString("FounderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Qualifications of the Founder.
        /// </summary>
        public static string FounderQualifications {
            get {
                return ResourceManager.GetString("FounderQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master in Linguistics from Umm Al-Qura University in Makkah Al-Mukarramah 2019..
        /// </summary>
        public static string FounderQualificationsValueLine1 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA in the Arabic language from Imam Muhammad bin Saud Islamic University, 2002.
        /// </summary>
        public static string FounderQualificationsValueLine2 {
            get {
                return ResourceManager.GetString("FounderQualificationsValueLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Founder&apos;s Specialty.
        /// </summary>
        public static string FounderSpecialty {
            get {
                return ResourceManager.GetString("FounderSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic language.
        /// </summary>
        public static string FounderSpecialtyValue {
            get {
                return ResourceManager.GetString("FounderSpecialtyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder&apos;s writings.
        /// </summary>
        public static string FounderWritings {
            get {
                return ResourceManager.GetString("FounderWritings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book of &quot;learn how to read the Noble Qur’an in thirty days&quot;.
        /// </summary>
        public static string FounderWritingsValue {
            get {
                return ResourceManager.GetString("FounderWritingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج الرابع.
        /// </summary>
        public static string FourthProgram {
            get {
                return ResourceManager.GetString("FourthProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم في هذا البرنامج اختبار الطالب في مجموعة من الكلمات، ويتم تحديد المهارات التي لا يتقنها الطالب، ووضع برنامج مختصر لعلاج المهارات التي لا يتقنها فقط، ثم يتم تدريب الطالب على كلمات من القرآن الكريم. وفي هذا البرنامج نعالج المشاكل القرائية من جذورها ولا نعالج الأخطاء في الكلمات التي يخطئ فيها الطالب..
        /// </summary>
        public static string FourthProgramDescription {
            get {
                return ResourceManager.GetString("FourthProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج تشخيص وعلاج الضعف في قراءه القران الكريم للمبتدئين.
        /// </summary>
        public static string FourthProgramHeading {
            get {
                return ResourceManager.GetString("FourthProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taqra Center.
        /// </summary>
        public static string IQRAACentre {
            get {
                return ResourceManager.GetString("IQRAACentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A centre is interested in teaching Arabic for all, aiming for facilitating learning Arabic reading and shortening the time required for that, to fulfil a hope that many Muslims have, which is reading the Noble Quran..
        /// </summary>
        public static string IQRAACentreP {
            get {
                return ResourceManager.GetString("IQRAACentreP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre is looking for the best ways and the most appropriate means to teach Arabic and be able to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP2 {
            get {
                return ResourceManager.GetString("IQRAACentreP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undoubtedly, the Arabic language is characterized by the proximity of its spoken sounds to its written letters and words, which facilitates and helps to learn Arabic reading thus learn to read the Noble Quran..
        /// </summary>
        public static string IQRAACentreP3 {
            get {
                return ResourceManager.GetString("IQRAACentreP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of downloads.
        /// </summary>
        public static string NumberOfDownloads {
            get {
                return ResourceManager.GetString("NumberOfDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم قراءة القران الكريم.
        /// </summary>
        public static string QuranReading {
            get {
                return ResourceManager.GetString("QuranReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليم مهارات القراءة العربية - 30 درسا.
        /// </summary>
        public static string ReadingSkillsLearn {
            get {
                return ResourceManager.GetString("ReadingSkillsLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دروس كتاب إتقان مهارات القراءة العربية الحرفية – 25 درسا.
        /// </summary>
        public static string ReadingSkillsLearn2 {
            get {
                return ResourceManager.GetString("ReadingSkillsLearn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دروس للانتقال من تعليم قراءة النص العربي الى قراءة الرسم العثماني..
        /// </summary>
        public static string ReadingSkillsLearn3 {
            get {
                return ResourceManager.GetString("ReadingSkillsLearn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITQAN (Mastering literal Arabic reading skills with some words pronunciation transliteration).
        /// </summary>
        public static string SecondBook {
            get {
                return ResourceManager.GetString("SecondBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الثاني.
        /// </summary>
        public static string SecondLevel {
            get {
                return ResourceManager.GetString("SecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Program.
        /// </summary>
        public static string SecondProgram {
            get {
                return ResourceManager.GetString("SecondProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program that helps students to correct their mistakes in reading the Noble Qur’an by addressing the causes of mistakes.Our goal in this program is to treat those mistakes from their roots. 
        ///It is a program that can be offered to both native Arabic speakers and non-Arabic speakers.
        /// </summary>
        public static string SecondProgramDescription {
            get {
                return ResourceManager.GetString("SecondProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم التعلم فيه بإحدى الطرق التالية:.
        /// </summary>
        public static string SecondProgramDescription2 {
            get {
                return ResourceManager.GetString("SecondProgramDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Reading of the Noble Quran..
        /// </summary>
        public static string SecondProgramHeading {
            get {
                return ResourceManager.GetString("SecondProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الفصل الحقيقي..
        /// </summary>
        public static string SecondProgramlist1 {
            get {
                return ResourceManager.GetString("SecondProgramlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الفصل الافتراضي الجماعي ( عبر منصات التعليم مثل زووم ).
        /// </summary>
        public static string SecondProgramlist2 {
            get {
                return ResourceManager.GetString("SecondProgramlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الفصل الافتراضي الفردي   ( عبر منصات التعليم مثل زووم ).
        /// </summary>
        public static string SecondProgramlist3 {
            get {
                return ResourceManager.GetString("SecondProgramlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الثالث.
        /// </summary>
        public static string ThirdLevel {
            get {
                return ResourceManager.GetString("ThirdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج الثالث.
        /// </summary>
        public static string ThirdProgram {
            get {
                return ResourceManager.GetString("ThirdProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وفيه ثلاثة مستويات:.
        /// </summary>
        public static string ThirdProgramDescription {
            get {
                return ResourceManager.GetString("ThirdProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج تعليم قراءه القران الكريم للمبتدئين.
        /// </summary>
        public static string ThirdProgramHeading {
            get {
                return ResourceManager.GetString("ThirdProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
    }
}
